# Generated by Django 4.1.7 on 2023-04-12 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresult',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
